pretrained: ./ckpt/model.pt

seed: 0
benchmark: false
mixed_precision: bf16

batch_size: 1
accum_iter: 1
epochs: 10
start_epoch: 0
lr: 1e-4
min_lr: 1e-6
warmup_epochs: 0.2
weight_decay: 0.05
clip_grad: 1.0

num_workers: 4
pin_mem: true
print_freq: 10
log_freq: 10
save_every_steps: 500
eval_every_steps: 500

save_dir: ./checkpoints
exp_name: event_finetune_global_local
logdir: ${save_dir}/${exp_name}/logs
output_dir: ${save_dir}/${exp_name}

model:
  img_size: 518
  patch_size: 14
  embed_dim: 1024
  event_hidden_dim: 32
  head_frames_chunk_size: 2
  branch_mode: global_local
  num_global_tokens: 16
  event_downsample: 4
  global_num_heads: 8
  global_inject_layers: [23]
  detail_hidden_dim: 128
  residual_scale: 0.1

train:
  unfreeze_heads: false
  unfreeze_aggregator_blocks: false
  unfreeze_aggregator_last_blocks: 0
  vggt_last_blocks_lr: 1e-5

loss:
  pose_weight: 1.0
  depth_weight: 1.0
  points_weight: 1.0
  normal_weight: 0.05
  event_edge_weight: 0.1
  detail_weight: 0.1
  points_loss_type: "l1"
  align_depth_scale: false
  depth_min: 1.0e-6
  depth_max: null

vis:
  save_every_steps: 200
  frame_index: 0
  sample_index: 0

data:
  root: /data1/lzh/dataset/reflective_raw
  num_views: 4
  resolution: [518, 392]
  fps: 120
  ldr_event_id: 5
  event_vis_out: null
  event_vis_bins: 10
  event_vis_only: false
  event_vis_max_batches: 1
  event_resize_method: voxel_antialias
  event_resize_bins: 10
  scene_names: null
  initial_scene_idx: 0
  active_scene_count: 3
  test_frame_count: 10

hydra:
  verbose: false
  run:
    dir: ${output_dir}
